"""
Vector search service — migrated from MongoDB to PostgreSQL.
Uses in-memory cosine similarity over product embeddings generated by Ollama.

Architecture:
  1. Fetch products from PostgreSQL (asyncpg)
  2. Generate embedding for user query (Ollama)
  3. Generate embeddings for products (cached in memory)
  4. Compute cosine similarity
  5. Return top-K results
"""
import asyncio
import numpy as np
from loguru import logger
from services.database import fetch_products_for_search
from services.embeddings import generate_embedding

# In-memory cache: { product_id: embedding_vector }
_product_embeddings: dict[str, list[float]] = {}
_cache_lock = asyncio.Lock()


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    """Compute cosine similarity between two vectors using NumPy."""
    a_arr = np.array(a)
    b_arr = np.array(b)
    dot_product = np.dot(a_arr, b_arr)
    norm_a = np.linalg.norm(a_arr)
    norm_b = np.linalg.norm(b_arr)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return float(dot_product / (norm_a * norm_b))


async def _ensure_product_embeddings(products: list[dict]) -> None:
    """Generate and cache embeddings for products that don't have one cached."""
    async with _cache_lock:
        missing = [p for p in products if p["id"] not in _product_embeddings]

        if not missing:
            return

        logger.info(f"Generating embeddings for {len(missing)} products...")

        for product in missing:
            try:
                text = f"{product['name']} {product.get('description', '')} {product.get('category', '')} {product.get('brand', '')}"
                embedding = await generate_embedding(text)
                _product_embeddings[product["id"]] = embedding
            except Exception as e:
                logger.warning(f"Failed to embed product {product['name']}: {e}")

        logger.info(f"Embedding cache size: {len(_product_embeddings)}")


async def search_products(query: str, top_k: int = 4) -> list[dict]:
    """
    Search products by semantic similarity.
    1. Fetch products from PostgreSQL
    2. Generate query embedding
    3. Compute cosine similarity against cached product embeddings
    4. Return top-K results sorted by similarity
    """
    try:
        # Step 1: Fetch products from PostgreSQL
        products = await fetch_products_for_search()

        if not products:
            logger.warning("No products found in database")
            return []

        # Step 2: Generate query embedding + ensure product embeddings
        query_embedding, _ = await asyncio.gather(
            generate_embedding(query),
            _ensure_product_embeddings(products),
        )

        # Step 3: Compute cosine similarity
        scored = []
        for product in products:
            product_emb = _product_embeddings.get(product["id"])
            if product_emb:
                score = _cosine_similarity(query_embedding, product_emb)
                scored.append((score, product))

        # Step 4: Sort by similarity (highest first)
        scored.sort(key=lambda x: x[0], reverse=True)
        top_results = scored[:top_k]

        # Return clean product dicts (no embeddings)
        results = []
        for score, product in top_results:
            results.append({
                **product,
                "similarity_score": round(score, 4),
            })

        logger.info(f"Search '{query}' → {len(results)} results (top score: {results[0]['similarity_score'] if results else 0})")
        return results

    except Exception as e:
        logger.error(f"Product search failed: {e}")
        return []


def clear_embedding_cache():
    """Clear the in-memory embedding cache (for admin/refresh)."""
    _product_embeddings.clear()
    logger.info("Embedding cache cleared")
